"""
05_figure_generation.py

Reproducible figure generation for the AD transcriptomic framework.

Uses outputs generated by:
    01_DAE_training.py
    02_AE16_K8_training.py
    03_gene_level_ML.py
    04_SHAP_analysis.py

Figures:
    DAE training loss
    AE16 training loss
    AE16 latent-space clustering
    Gene-level ML ROC curves
    SHAP global importance

All figures are saved at 600 dpi.
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc


# ============================================================
# 1. PATHS
# ============================================================

ROOT = Path(__file__).resolve().parent.parent
RESULT_DIR = ROOT / "results"
FIGURE_DIR = ROOT / "figures"

FIGURE_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# 2. DAE TRAINING LOSS
# ============================================================

def plot_dae_loss():

    file = RESULT_DIR / "DAE_training_validation_loss.csv"

    if not file.exists():
        print("[SKIP] DAE loss file not found.")
        return

    df = pd.read_csv(file)

    plt.figure(figsize=(6, 4))

    if "epoch" in df.columns:
        x = df["epoch"]
    else:
        x = np.arange(1, len(df) + 1)

    if "loss" in df.columns:
        plt.plot(x, df["loss"], label="Training loss")

    if "train_loss" in df.columns:
        plt.plot(x, df["train_loss"], label="Training loss")

    if "val_loss" in df.columns:
        plt.plot(x, df["val_loss"], label="Validation loss")

    plt.xlabel("Epoch")
    plt.ylabel("MSE loss")
    plt.title("DAE training")
    plt.legend(frameon=False)
    plt.tight_layout()

    output = FIGURE_DIR / "DAE_training_loss.png"

    plt.savefig(output, dpi=600, bbox_inches="tight")
    plt.close()

    print("Saved:", output)


# ============================================================
# 3. AE16 TRAINING LOSS
# ============================================================

def plot_ae16_loss():

    file = RESULT_DIR / "AE16_training_loss.csv"

    if not file.exists():
        print("[SKIP] AE16 loss file not found.")
        return

    df = pd.read_csv(file)

    plt.figure(figsize=(6, 4))

    plt.plot(df["epoch"], df["loss"])

    plt.xlabel("Epoch")
    plt.ylabel("MSE loss")
    plt.title("AE16 training")
    plt.tight_layout()

    output = FIGURE_DIR / "AE16_training_loss.png"

    plt.savefig(output, dpi=600, bbox_inches="tight")
    plt.close()

    print("Saved:", output)


# ============================================================
# 4. AE16 LATENT SPACE
#
# Simple reproducibility plot using z1 and z2.
# Clustering itself was performed in the full 16-D latent space.
# ============================================================

def plot_latent_clusters():

    file = RESULT_DIR / "AE16_K8_results.csv"

    if not file.exists():
        print("[SKIP] AE16 K8 result file not found.")
        return

    df = pd.read_csv(file)

    required = ["z1", "z2", "cluster_kmeans_k8"]

    if not all(c in df.columns for c in required):
        print("[SKIP] Required latent columns not found.")
        return

    plt.figure(figsize=(6, 5))

    scatter = plt.scatter(
        df["z1"],
        df["z2"],
        c=df["cluster_kmeans_k8"],
        s=8,
        alpha=0.7
    )

    plt.xlabel("Latent dimension 1")
    plt.ylabel("Latent dimension 2")
    plt.title("AE16 latent representation")

    cbar = plt.colorbar(scatter)
    cbar.set_label("K-means cluster")

    plt.tight_layout()

    output = FIGURE_DIR / "AE16_K8_latent_space.png"

    plt.savefig(output, dpi=600, bbox_inches="tight")
    plt.close()

    print("Saved:", output)


# ============================================================
# 5. GENE-LEVEL ML ROC CURVES
# ============================================================

def plot_ml_roc():

    file = RESULT_DIR / "gene_level_ML_OOF.csv"

    if not file.exists():
        print("[SKIP] ML OOF file not found.")
        return

    df = pd.read_csv(file)

    y = df["observed"].values

    models = ["XGB", "RF", "KNN", "DT"]

    plt.figure(figsize=(6, 6))

    found = False

    for model in models:

        col = f"{model}_probability"

        if col not in df.columns:
            continue

        probability = df[col].values

        fpr, tpr, _ = roc_curve(y, probability)

        roc_auc = auc(fpr, tpr)

        plt.plot(
            fpr,
            tpr,
            label=f"{model} (AUC={roc_auc:.3f})"
        )

        found = True

    if not found:
        plt.close()
        print("[SKIP] No ML probability columns found.")
        return

    plt.plot(
        [0, 1],
        [0, 1],
        linestyle="--"
    )

    plt.xlabel("False positive rate")
    plt.ylabel("True positive rate")
    plt.title("Gene-level classification")
    plt.legend(frameon=False)
    plt.tight_layout()

    output = FIGURE_DIR / "Gene_level_ML_ROC.png"

    plt.savefig(output, dpi=600, bbox_inches="tight")
    plt.close()

    print("Saved:", output)


# ============================================================
# 6. SHAP GLOBAL IMPORTANCE
# ============================================================

def plot_shap_importance():

    file = RESULT_DIR / "SHAP_feature_importance.csv"

    if not file.exists():
        print("[SKIP] SHAP importance file not found.")
        return

    df = pd.read_csv(file)

    df = df.sort_values(
        "mean_abs_SHAP",
        ascending=False
    ).head(20)

    df = df.iloc[::-1]

    plt.figure(figsize=(7, 6))

    plt.barh(
        df["feature"],
        df["mean_abs_SHAP"]
    )

    plt.xlabel("Mean |SHAP value|")
    plt.ylabel("Feature")
    plt.title("Global SHAP importance")
    plt.tight_layout()

    output = FIGURE_DIR / "SHAP_global_importance.png"

    plt.savefig(output, dpi=600, bbox_inches="tight")
    plt.close()

    print("Saved:", output)


# ============================================================
# 7. MAIN
# ============================================================

def main():

    print("=" * 70)
    print("FIGURE GENERATION")
    print("=" * 70)

    plot_dae_loss()
    plot_ae16_loss()
    plot_latent_clusters()
    plot_ml_roc()
    plot_shap_importance()

    print("\n" + "=" * 70)
    print("FIGURE GENERATION COMPLETED")
    print("=" * 70)

    print("Output directory:")
    print(FIGURE_DIR)


if __name__ == "__main__":
    main()